export default() => {
  return {
    A: {
      id: "A",
      composante: "AL",
      description: "Aléas",
      composition: [ "A1", "A2", "A3" ],
      methode: "Maximum des indicateurs thématiques (érosion, submersion, migration dunaire)",
      niveau: 3,
      acronyme: "AL",
      nom: "Composante des aléas",
      service: ""
    },
    A1: {
      id: "A1",
      composante: "AL",
      description: "Erosion",
      composition: [ "A101" ],
      methode: "Distance érodée par an par 100m linéaires",
      niveau: 2,
      acronyme: "ERO",
      nom: "Erosion",
      service: ""
    },
    A101: {
      id: "A101",
      composante: "AL",
      description: "Distance érodée par an par 100m linéaires",
      niveau: 1,
      acronyme: "DIST",
      nom: "Distance",
      service: "",
      thematique: "ERO"
    },
    A102: {
      id: "A102",
      composante: "AL",
      description: "Surface érodée par an par 100m linéaires",
      niveau: 1,
      acronyme: "SURF",
      nom: "Surface",
      service: "",
      thematique: "ERO"
    },
    A103: {
      id: "A103",
      composante: "AL",
      description: "Volume érodé par an par 100m linéaires",
      niveau: 1,
      acronyme: "VOL",
      nom: "Volume",
      service: "",
      thematique: "ERO"
    },
    A2: {
      id: "A2",
      composante: "AL",
      description: "Submersion",
      composition: [ "A201", "A202" ],
      methode: "Maximum des indicateurs (submersion et paquets de mer)",
      niveau: 2,
      acronyme: "SUB",
      nom: "Submersion",
      service: ""
    },
    A201: {
      id: "A201",
      composante: "AL",
      description: "Hauteur de submersion",
      niveau: 1,
      acronyme: "HAUT",
      nom: "Hauteur",
      service: "",
      thematique: "SUB"
    },
    A202: {
      id: "A202",
      composante: "AL",
      description: "Linéaire exposé aux paquets de mer et aux écoulements",
      niveau: 1,
      acronyme: "PAQ",
      nom: "Paquets de mer",
      service: "",
      thematique: "SUB"
    },
    A3: {
      id: "A3",
      composante: "AL",
      description: "Migration dunaire",
      composition: [ "A301" ],
      methode: "",
      niveau: 2,
      acronyme: "MIGR",
      nom: "Migration dunaire",
      service: ""
    },
    A301: {
      id: "A301",
      composante: "AL",
      description: "Vitesse de migration dunaire",
      niveau: 1,
      acronyme: "VIT",
      nom: "Vitesse",
      service: "",
      thematique: "MIGR"
    },
    E: {
      id: "E",
      composante: "EN",
      description: "Enjeux",
      composition: [ "E101",    "E102",    "E103",    "E104",    "E106",    "E108",    "E109",   "E201" ,   "E202",    "E203",   "E204" ,   "E301",    "E303" , "E304",    "E305" ,   "E306" ],
      methode: "Moyenne géométrique des indicateurs",
      niveau: 3,
      acronyme: "EN",
      nom: "Composante des enjeux",
      service: ""
    },
    E1: {
      id: "E1",
      composante: "EN",
      description: "Humains",
      composition: [ "E101", "E102", "E103", "E104", "E106", "E108", "E109" ], 
      methode: "Maximum des indicateurs",
      niveau: 2,
      acronyme: "HUM",
      nom: "Humains",
      service: ""
    },
    E101: {
      id: "E101",
      composante: "EN",
      description: "Nombre d'habitants",
      niveau: 1,
      acronyme: "POP",
      nom: "Population",
      service: "https://tucuxi.univ-brest.fr/attachments/download/669/E101_ENHUMPOP.pdf",
      thematique: "HUM"
    },
    E102: {
      id: "E102",
      composante: "EN",
      description: "Nombre de bâti résidentiel",
      niveau: 1,
      acronyme: "BATI",
      nom: "Logements",
      service: "https://tucuxi.univ-brest.fr/attachments/download/670/E102_ENHUMBATI.pdf",
      thematique: "HUM"
    },
    E103: {
      id: "E103",
      composante: "EN",
      description: "Capacité d'accueil des Etablissements Recevant du Public",
      niveau: 1,
      acronyme: "ERP",
      nom: "Capacité d'accueil",
      service: "https://tucuxi.univ-brest.fr/attachments/download/671/E103_ENHUMERP.pdf",
      thematique: "HUM"
    },
    E104: {
      id: "E104",
      composante: "EN",
      description: "Nombre de personnes de moins de 10 ou de plus de plus de 65 ans",
      niveau: 1,
      acronyme: "PERVUL-NB",
      nom: "Population vulnérable (nombre)",
      service: "",
      thematique: "HUM"
    },
    E105: {
      id: "E105",
      composante: "EN",
      description: "Pourcentage de personnes de moins de 10 ou de plus de plus de 65 ans",
      niveau: 1,
      acronyme: "PERVUL-PCT",
      nom: "Population vulnérable (%)",
      service: "https://tucuxi.univ-brest.fr/attachments/download/672/E105_ENHUMPERVUL.pdf",
      thematique: "HUM"
    },
    E106: {
      id: "E106",
      composante: "EN",
      description: "Nombre de ménages à bas revenu",
      niveau: 1,
      acronyme: "BAREV-NB",
      nom: "Population pauvre (nombre)",
      service: "",
      thematique: "HUM"
    },
    E107: {
      id: "E107",
      composante: "EN",
      description: "Part des ménages à bas revenu",
      niveau: 1,
      acronyme: "BAREV-PCT",
      nom: "Population pauvre (%)",
      service: "https://tucuxi.univ-brest.fr/attachments/download/673/E107_ENHUMBAREV.pdf",
      thematique: "HUM"
    },
    E108: {
      id: "E108",
      composante: "EN",
      description: "Part des résidences secondaires",
      niveau: 1,
      acronyme: "SECOND",
      nom: "Population temporaire",
      service: "https://tucuxi.univ-brest.fr/attachments/download/668/E108_ENHUMSECOND.pdf",
      thematique: "HUM"
    },
    E109: {
      id: "E109",
      composante: "EN",
      description: "Capacité d’hébergement touristique",
      niveau: 1,
      acronyme: "TOURIST",
      nom: "Tourisme",
      service: "https://tucuxi.univ-brest.fr/attachments/download/674/E109_ENHUMTOURIS.pdf",
      thematique: "HUM"
    },
    E2: {
      id: "E2",
      composante: "EN",
      description: "Economiques",
      composition: [ "E201", "E202", "E203", "E204" ],
      methode: "Maximum des indicateurs",
      niveau: 2,
      acronyme: "ECO",
      nom: "Economiques",
      service: ""
    },
    E201: {
      id: "E201",
      composante: "EN",
      description: "Nombre de travailleurs",
      niveau: 1,
      acronyme: "TRAV",
      nom: "Emploi",
      service: "https://tucuxi.univ-brest.fr/attachments/download/675/E201_ENECOTRAV.pdf",
      thematique: "ECO"
    },
    E202: {
      id: "E202",
      composante: "EN",
      description: "Valeur immobilière moyenne (m²)",
      niveau: 1,
      acronyme: "VIMMO",
      nom: "Immobilier",
      service: "",
      thematique: "ECO"
    },
    E203: {
      id: "E203",
      composante: "EN",
      description: "Diversité des activités",
      niveau: 1,
      acronyme: "DIV",
      nom: "Résilience économique",
      service: "",
      thematique: "ECO"
    },
    E204: {
      id: "E204",
      composante: "EN",
      description: "Taux de fonction touristique (lits touristiques / habitants)",
      niveau: 1,
      acronyme: "TOUR-TX",
      nom: "Tourisme",
      service: "",
      thematique: "ECO"
    },
    E205: {
      id: "E205",
      composante: "EN",
      description: "Surface occupée par l'agriculture",
      niveau: 1,
      acronyme: "AGRI",
      nom: "Agriculture",
      service: "https://tucuxi.univ-brest.fr/attachments/download/676/E205_ENECOAGRI.pdf",
      thematique: "ECO"
    },
    E3: {
      id: "E3",
      composante: "EN",
      description: "Structurels",
      composition: [ "E301", "E302", "E303", "E304", "E305"],  
      methode: "Maximum des indicateurs",
      niveau: 2,
      acronyme: "STR",
      nom: "Structurels",
      service: ""
    },
    E301: {
      id: "E301",
      composante: "EN",
      description: "Localisation des établissements industriels à risque",
      niveau: 1,
      acronyme: "INDRISQ",
      nom: "Suraccident",
      service: "https://tucuxi.univ-brest.fr/attachments/download/677/E301_ENSTRINDRISQ.pdf",
      thematique: "STR"
    },
    E302: {
      id: "E302",
      composante: "EN",
      description: "Présence/Nombre de points sensibles",
      niveau: 1,
      acronyme: "NEVRAL",
      nom: "Sensiblité du réseau",
      service: "",
      thematique: "STR"
    },
    E303: {
      id: "E303",
      composante: "EN",
      description: "Part du linéaire côtier artificialisé à l'aide d'ouvrages de type digue",
      niveau: 1,
      acronyme: "DIG",
      nom: "Artificialisation",
      service: "https://tucuxi.univ-brest.fr/attachments/download/698/E303_ENSTRDIG.pdf",
      thematique: "STR"
    },
    E304: {
      id: "E304",
      composante: "EN",
      description: "Localisation du bâti résidentiel sans étage refuge",
      niveau: 1,
      acronyme: "REFUG",
      nom: "Logements à risque",
      service: "",
      thematique: "STR"
    },
    E305: {
      id: "E305",
      composante: "EN",
      description: "Proximité d'établissements de secours",
      niveau: 1,
      acronyme: "SECOUR",
      nom: "Secours",
      service: "https://tucuxi.univ-brest.fr/attachments/download/678/EN-SECOUR.pdf",
      thematique: "STR"
    },
    E306: {
      id: "E306",
      composante: "EN",
      description: "Localisation du patrimoine culturel",
      niveau: 1,
      acronyme: "PATRIM",
      nom: "Patrimoine culturel",
      service: "https://tucuxi.univ-brest.fr/attachments/download/699/E306_ENPATPATRIM.pdf",
      thematique: "STR"
    },
    G: {
      id: "G",
      composante: "GE",
      description: "Gestion",
      composition: [ "G1", "G2", "G3" ],
      methode: "Maximum des indicateurs (prévention et anticipation, sensibilisation, gestion de crise)", 
      niveau: 3,
      acronyme: "GE",
      nom: "Composante de la gestion",
      service: ""
    },
    G1: {
      id: "G1",
      composante: "GE",
      description: "Prévention",
      composition: [ "G101", "G103", "G104", "G105", "G106", "G108", "G110" ],
      methode: "Maximum des indicateurs",
      niveau: 2,
      acronyme: "PRE",
      nom: "Prévention",
      service: ""
    },
    G101: {
      id: "G101",
      composante: "GE",
      description: "Contraintes de constructibilité en zone d’aléas",
      niveau: 1,
      acronyme: "URBA",
      nom: "Urbanisme",
      service: "https://tucuxi.univ-brest.fr/attachments/download/697/Urba_G101.pdf",
      thematique: "PRE"
    },
    G102: {
      id: "G102",
      composante: "GE",
      description: "Etat du PPRL",
      niveau: 1,
      acronyme: "PPRL",
      nom: "PPRL",
      service: "https://tucuxi.univ-brest.fr/attachments/download/693/PPRL_G102.pdf",
      thematique: "PRE"
    },
    G103: {
      id: "G103",
      composante: "GE",
      description: "Mise en place de la compétence",
      niveau: 1,
      acronyme: "GEMAPI1",
      nom: "Compétence GEMAPI",
      service: "https://tucuxi.univ-brest.fr/attachments/download/687/GEMAPI_G103.pdf",
      thematique: "PRE"
    },
    G104: {
      id: "G104",
      composante: "GE",
      description: "Etat des ouvrages",
      niveau: 1,
      acronyme: "GEMAPI2",
      nom: "Etat des ouvrages",
      service: "https://tucuxi.univ-brest.fr/attachments/download/700/OUV_GEMAPI2_G104.pdf",
      thematique: "PRE"
    },
    G105: {
      id: "G105",
      composante: "GE",
      description: "Investissement humain sur les risques côtiers",
      niveau: 1,
      acronyme: "HUM",
      nom: "Investissement humain",
      service: "https://tucuxi.univ-brest.fr/attachments/download/682/CapHum_G105.pdf",
      thematique: "PRE"
    },
    G106: {
      id: "G106",
      composante: "GE",
      description: "Démarche locale de gestion des risques",
      niveau: 1,
      acronyme: "STRATE",
      nom: "Démarche locale",
      service: "https://tucuxi.univ-brest.fr/attachments/download/696/Strate_G106.pdf",
      thematique: "PRE"
    },
    G107: {
      id: "G107",
      composante: "GE",
      description: "Intégration différents acteurs de la démarche locale",
      niveau: 1,
      acronyme: "ACTEUR",
      nom: "Intégration des acteurs",
      service: "https://tucuxi.univ-brest.fr/attachments/download/688/IntActDem_G107.pdf",
      thematique: "PRE"
    },
    G108: {
      id: "G108",
      composante: "GE",
      description: "Intégration extraterritoriale",
      niveau: 1,
      acronyme: "EXTRA",
      nom: "Intégration extraterritoriale",
      service: "",
      thematique: "PRE"
    },
    G109: {
      id: "G109",
      composante: "GE",
      description: "Actions dans chaque axe du PAPI",
      niveau: 1,
      acronyme: "PAPI1",
      nom: "Actions",
      service: "https://tucuxi.univ-brest.fr/attachments/download/679/ActPAPI1_G109.pdf",
      thematique: "PRE"
    },
    G110: {
      id: "G110",
      composante: "GE",
      description: "Mise en œuvre des actions du PAPI",
      niveau: 1,
      acronyme: "PAPI2",
      nom: "Mise en œuvre",
      service: "https://tucuxi.univ-brest.fr/attachments/download/690/MeOPAPI2_G110.pdf",
      thematique: "PRE"
    },
    G111: {
      id: "G111",
      composante: "GE",
      description: "Etat de la stratégie locale (relocalisation)",
      niveau: 1,
      acronyme: "RELOC",
      nom: "Stratégie locale",
      service: "https://tucuxi.univ-brest.fr/attachments/download/694/Reloc_G111.pdf",
      thematique: "PRE"
    },
    G2: {
      id: "G2",
      composante: "GE",
      description: "Sensibilisation",
      composition: [ "G201", "G202", "G203", "G204", "G206" ],
      methode: "Maximum des indicateurs",
      niveau: 2,
      acronyme: "SEN",
      nom: "Sensibilisation",
      service: ""
    },
    G201: {
      id: "G201",
      composante: "GE",
      description: "Evènements de sensibilisation dans les établissements scolaires",
      niveau: 1,
      acronyme: "SCOL",
      nom: "Scolaires",
      service: "https://tucuxi.univ-brest.fr/attachments/download/686/EvetScol_G201.pdf",
      thematique: "SEN"
    },
    G202: {
      id: "G202",
      composante: "GE",
      description: "Présence d’associations sur les risques côtiers",
      niveau: 1,
      acronyme: "ASSO",
      nom: "Association",
      service: "https://tucuxi.univ-brest.fr/attachments/download/681/Asso_G202.pdf",
      thematique: "SEN"
    },
    G203: {
      id: "G203",
      composante: "GE",
      description: "Publications scientifiques sur les risques côtiers",
      niveau: 1,
      acronyme: "PUBLI",
      nom: "Publications scientifiques",
      service: "https://tucuxi.univ-brest.fr/attachments/download/692/PblSci_G203.pdf",
      thematique: "SEN"
    },
    G204: {
      id: "G204",
      composante: "GE",
      description: "Repères inondation et de recul du trait de côte",
      niveau: 1,
      acronyme: "REP",
      nom: "Repères",
      service: "https://tucuxi.univ-brest.fr/attachments/download/695/Rep_G204.pdf",
      thematique: "SEN"
    },
    G205: {
      id: "G205",
      composante: "GE",
      description: "Modes de diffusion du DICRIM ",
      niveau: 1,
      acronyme: "DICRIM1",
      nom: "Diffusion",
      service: "https://tucuxi.univ-brest.fr/attachments/download/684/DICRIM1_G205.pdf",
      thematique: "SEN"
    },
    G206: {
      id: "G206",
      composante: "GE",
      description: "Analyse pédagogique du DICRIM",
      niveau: 1,
      acronyme: "DICRIM2",
      nom: "Pédagogie",
      service: "https://tucuxi.univ-brest.fr/attachments/download/685/DICRIM2_G206.pdf",
      thematique: "SEN"
    },
    G3: {
      id: "G3",
      composante: "GE",
      description: "Gestion de crise",
      composition: [ "G301", "G302", "G303" ],
      methode: "Maximum des indicateurs",
      niveau: 2,
      acronyme: "CRI",
      nom: "Gestion de crise",
      service: ""
    },
    G301: {
      id: "G301",
      composante: "GE",
      description: "Mode d’alerte de la population",
      niveau: 1,
      acronyme: "ALERTE",
      nom: "Alerte",
      service: "https://tucuxi.univ-brest.fr/attachments/download/680/Alerte_G301.pdf",
      thematique: "CRI"
    },
    G302: {
      id: "G302",
      composante: "GE",
      description: "Intégration du SDIS dans le PCS",
      niveau: 1,
      acronyme: "SDIS",
      nom: "Intégration",
      service: "https://tucuxi.univ-brest.fr/attachments/download/689/IntSDIS_G302.pdf",
      thematique: "CRI"
    },
    G303: {
      id: "G303",
      composante: "GE",
      description: "Mise à jour du PCS",
      niveau: 1,
      acronyme: "PCS",
      nom: "Plan Communal de Sauvegarde",
      service: "https://tucuxi.univ-brest.fr/attachments/download/691/MJ_PCS_G303.pdf",
      thematique: "CRI"
    },
    R: {
      id: "R",
      composante: "RE",
      description: "Représentations", 
      niveau: 3,
      acronyme: "RE",
      composition: [ "R1", "R2", "R3" ],
      methode: "Maximum des indicateurs (conscience des aléas, dimension sociale du lieu, perception de la gestion)",
      nom: "Composante des représentations",
      service: ""
    },
    R1: {
      id: "R1",
      composante: "RE",
      description: "Conscience des aléas",
      composition: [ "R101", "R103", "R104", "R105" ],
      methode: "Maximum des indicateurs",
      niveau: 2,
      acronyme: "COAL",
      nom: "Conscience des aléas",
      service: ""
    },
    R101: {
      id: "R101",
      composante: "RE",
      description: "Sources d'information dont disposent les individus",
      niveau: 1,
      acronyme: "COM",
      nom: "Sources d'information",
      service: "",
      thematique: "COAL"
    },
    R102: {
      id: "R102",
      composante: "RE",
      description: "Expérience des risques",
      niveau: 1,
      acronyme: "ER",
      nom: "Expérience",
      service: "",
      thematique: "COAL"
    },
    R103: {
      id: "R103",
      composante: "RE",
      description: "Information active",
      niveau: 1,
      acronyme: "IA",
      nom: "Information active",
      service: "",
      thematique: "COAL"
    },
    R104: {
      id: "R104",
      composante: "RE",
      description: "Identification des risques côtiers ",
      niveau: 1,
      acronyme: "IR",
      nom: "Identification",
      service: "",
      thematique: "COAL"
    },
    R105: {
      id: "R105",
      composante: "RE",
      description: "Identification personnelle des risques côtiers",
      niveau: 1,
      acronyme: "IP",
      nom: "Identification personnelle",
      service: "",
      thematique: "COAL"
    },
    R106: {
      id: "R106",
      composante: "RE",
      description: "Niveau d’inquiétude",
      niveau: 1,
      acronyme: "NI",
      nom: "Inquiétude",
      service: "",
      thematique: "COAL"
    },
    R107: {
      id: "R107",
      composante: "RE",
      description: "Identification personnelle",
      niveau: 1,
      acronyme: "IP",
      nom: "Identification personnelle",
      service: "",
      thematique: "COAL"
    },
    R2: {
      id: "R2",
      composante: "RE",
      description: "Dimension sociale",
      composition: [ "R201", "R202", "R203" ], 
      methode: "Maximum des indicateurs",
      niveau: 2,
      acronyme: "DISO",
      nom: "Dimension sociale",
      service: ""
    },
    R201: {
      id: "R201",
      composante: "RE",
      description: "Dépendance, attachement et identité du lieu",
      niveau: 1,
      acronyme: "DP",
      nom: "Sens du lieu",
      service: "",
      thematique: "DISO"
    },
    R202: {
      id: "R202",
      composante: "RE",
      description: "Valorisation sociale du cadre de vie littorale",
      niveau: 1,
      acronyme: "VALOR",
      nom: "Valorisation",
      service: "",
      thematique: "DISO"
    },
    R203: {
      id: "R203",
      composante: "RE",
      description: "Vie associative en lien avec les risques côtiers",
      niveau: 1,
      acronyme: "ASSORIS",
      nom: "Association",
      service: "",
      thematique: "DISO"
    },
    R204: {
      id: "R204",
      composante: "RE",
      description: "Activités en lien avec la mer",
      niveau: 1,
      acronyme: "ACTMER",
      nom: "Activités",
      service: "",
      thematique: "DISO"
    },
    R3: {
      id: "R3",
      composante: "RE",
      description: "Perception de la gest°",
      composition: [ "R301", "R302", "R303" ],
      methode: "Maximum des indicateurs",
      niveau: 2,
      acronyme: "GEST",
      nom: "Perception de la gestion",
      service: ""
    }, 
    R301: {
      id: "R301",
      composante: "RE",
      description: "Pratiques individuelles de prévention et/ou de protection",
      niveau: 1,
      acronyme: "IND",
      nom: "Pratiques individuelles",
      service: "",
      thematique: "GEST"
    },
    R302: {
      id: "R302",
      composante: "RE",
      description: "Pratiques collectives de prévention et/ou de protection",
      niveau: 1,
      acronyme: "CO",
      nom: "Pratiques collectives",
      service: "",
      thematique: "GEST"
    },
    R303: {
      id: "R303",
      composante: "RE",
      description: "Confiance et légitimité dans la gestion des risques côtiers",
      niveau: 1,
      acronyme: "GES",
      nom: "Confiance et légitimité",
      service: "",
      thematique: "GEST"
    },
    I: {
      id: "I",
      composante: "IT",
      composition: [ "A", "E", "G", "R" ],
      description: "Indices",
      niveau: 3,
      acronyme: "IT",
      nom: "Indices composites",
      service: ""
    },
    I1: {
      id: "I1",
      composante: "IT",
      composition: [ "A", "E", "G", "R" ],
      description: "Globaux",
      niveau: 2,
      acronyme: "SYST",
      nom: "SYST",
      service: ""
    },
    I101: {
      id: "I101",
      composante: "IT",
      nom: "Systémique",
      description: "Aléas * Enjeux * (6-Gestion + 6-Représentation)",
      composition: [ "A", "E", "G", "R" ],
      methode: "Aléas * Enjeux * (6-Gestion + 6-Représentation)",
      niveau: 1,
      acronyme: "GLOB",
      service: "",
      thematique: "SYST"
    }, 
    I102: {
      id: "I102",
      composante: "IT",
      nom: "Risque",
      composition: [ "A", "E" ],
      methode: "Normalisation du produit entre les aléas et les enjeux",
      description: "Aléas * Enjeux",
      niveau: 1,
      acronyme: "RISK",
      service: "",
      thematique: "SYST"
    },
    I2: {
      id: "I2",
      composante: "IT",
      composition: [ "A", "E", "G", "R" ],
      description: "Transverses",
      niveau: 2,
      acronyme: "TRANS",
      nom: "TRANS",
      service: ""
    },
    I221: {
      id: "I221",
      composante: "IT",
      nom: "Opérationnel",
      composition: [ "A", "E303", "E304", "G104", "G204", "G301", "R101", "R103", "R201" ],
      methode: "Normalisation par la maximum de la racine du produit des indicateurs discrétisés sur la racine du nombre d'indicateurs",
      description: "Actions possibles dans l'immédiat",
      niveau: 1,
      acronyme: "OPE",
      service: "",
      thematique: "TRANS"
    },
    I231: {
      id: "I231",
      composante: "IT",
      nom: "Stratégique",
      composition: [ "A", "E103", "E202", "E203", "E301", "E302", "G101", "G106", "G108", "G302", "R104", "R105", "R201", "R303" ],
      methode: "Normalisation par la maximum de la racine du produit des indicateurs discrétisés sur la racine du nombre d'indicateurs",
      description: "Actions possibles à terme",
      niveau: 1,
      acronyme: "STRAT",
      service: "",
      thematique: "TRANS"
    },
    I201: {
      id: "I201",
      composante: "IT",
      description: "Vulnérabilité du bâti (racine)",
      composition: [ "A1", "A2" , "E303" ,  "E304" ,  "G3" ,  "E102" ],
      methode: "Normalisation par la maximum de la racine du produit des indicateurs discrétisés sur la racine du nombre d'indicateurs",
      niveau: 1,
      acronyme: "BATI",
      nom: "Matériel (racine)",
      service: "",
      thematique: "TRANS"
    }, 
    I202: {
      id: "I202",
      composante: "IT",
      nom: "Matériel (somme)",
      description: "Vulnérabilité du bâti (moyenne)",
      composition: [ "A1", "A2" , "E303" ,  "E304" ,  "G3" ,  "E102" ],
      methode: "Moyenne arithmétique des indicateurs",
      niveau: 1,
      acronyme: "BATISOM",
      service: "",
      thematique: "TRANS"
    },
    I203: {
      id: "I203",
      composante: "IT",
      nom: "Matériel (produit)",
      description: "Vulnérabilité du bâti (produit)",
      composition: [ "A1", "A2" , "E303" ,  "E304" ,  "G3" ,  "E102" ],
      methode: "Produit des indicateurs",
      niveau: 1,
      acronyme: "BATIPROD",
      service: "",
      thematique: "TRANS"
    },
    I211: {
      id: "I211",
      composante: "IT",
      nom: "Submersion (racine)",
      composition: [ "A201", "E303", "E101", "E102", "E104", "E106", "G101", "G106" ],
      methode: "Normalisation par la maximum de la racine du produit des indicateurs discrétisés sur la racine du nombre d'indicateurs",
      description: "Vulnérabilité à la submersion (racine)",
      niveau: 1,
      acronyme: "SUB",
      service: "",
      thematique: "TRANS"
    },
    I212: {
      id: "I212",
      composante: "IT",
      nom: "Submersion (somme)",
      description: "Vulnérabilité à la submersion (moyenne)",
      composition: [ "A201", "E303", "E101", "E102", "E104", "E106", "G101", "G106" ],
      methode: "Moyenne arithmétique des indicateurs",
      niveau: 1,
      acronyme: "SUBSOM",
      service: "",
      thematique: "TRANS"
    },
    I213: {
      id: "I213",
      composante: "IT",
      nom: "Submersion (produit)",
      description: "Vulnérabilité à la submersion (produit)",
      composition: [ "A201", "E303", "E101", "E102", "E104", "E106", "G101", "G106" ],
      methode: "Produit des indicateurs",
      niveau: 1,
      acronyme: "SUMPROD",
      service: "",
      thematique: "TRANS"
    },
  }
};
